### ISSUE TITLE
RTU - Execute Cycle

### ISSUE THREAD

**Issue by irahhari** [digital-design-snu/Emulator#5]
```
CUD 02
RTU
```

Execute Cycle
[SP]<-[SP]+1, [PC]<-[[SP]+1], this is the action, but the PC is not updated with the incremented value SP is pointing to. For example, Address FF = 01, SP = FE, when I execute RTU, SP should be incremented and is working fine. But the next action is not working correctly. After execute cycle, this is the output: SP = FF, PC = 01. This mean, HEX code at address 01 = 02, which is an operand of CUD is considered as an OP Code and is executing that.

**Comment by command-paul** [comment]
Hey @irahhari Thanks for opening this issue, I narrowed the issue down to an incorrect sequence of control bits for the unconditional Call Instructions and have implemented fix(0a2a6fc121bb014bf68b5805084428b2561e26fd) that has behavior similar to that of the Conditional variants that are executing correctly. If you can verify the behavior of this patch at your end by updating the machcode.bin file in your local rnbip python package instillation Ill proceed to update the PyPi package.

**Comment by irahhari** [comment]
Hi @command-paul, I checked it working after the patch. It is working fine.
